version: '3.8'

services:
    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
    booksapi:
        image: booksapi
        restart: always
        ports:
            - 8000:8000
        links:
            - mongo
        environment:
            - DB_URL=mongodb://mongo:27017
            - DB_NAME=appDBName